### ISSUE TITLE
Expo support?

### ISSUE THREAD

**Issue by Norfeldt** [FormidableLabs/react-native-owl#116]
It's clear from the docs that this works if you build your own app. But what if you really wanna stay in the Expo eco system? 

Is there an EAS plugin solution that makes it possible to make EAS build it with a custom dev client?

**Comment by robwalkerco** [comment]
Hi @Norfeldt, I haven't personally been able to test with EAS yet, and I don't have access to EAS or experience in using it.
From what I understand about EAS dev clients, I believe it should be possible to setup though.
We are open to PR's and/or doc updates if you are able to help out with any Expo setup/testing. 
There is able some discussion in #101 where I believe some people have managed to use Owl and Expo together with some success.

**Comment by Norfeldt** [comment]
Thank you for the link to the thread 👍

**Comment by robwalkerco** [comment]
Closing this issue as discussion has moved to #101
