### ISSUE TITLE
Error running on Bitrise CI

### ISSUE THREAD

**Issue by EJohnF** [FormidableLabs/react-native-owl#118]
Hello,

Thank you for the library! I tried it, initially looks good but I've got a problem running it on CI.
Getting error: `Error: Command failed with exit code 149: xcrun simctl status_bar iPhone 11 override --time 9:41`

Seems like it isn't possible to run in headless mode? 
(we already have successfully running detox tests, but looking into visual regression tests)

**Comment by robwalkerco** [comment]
My guess is that the `xcrun` utility is missing on Bitrise.
If it's not available by default in their environment, then you may need to install xcode tools or similar. I'm not experienced with Bitrise, so you may need to refer to their documentation or support to see how to do that. Hopefully the GitHub action example we have if helpful as an example for getting the tests to run on CI generally. 

You can attempt to run `xcrun simctl status_bar iPhone 11 override --time 9:41` directly in the Bitrise environment to verify that it works.

**Comment by EJohnF** [comment]
Thanks, will investigate more with Bitrise
