### ISSUE TITLE
[iOS] Test on GitHub Action doesn't seem to change the iOS simulator time

### ISSUE THREAD

**Issue by shadowsheep1** [FormidableLabs/react-native-owl#138]
I'm trying to integrate your great tool with GA in this [test repo](https://github.com/shadowsheep1/TestRNOwlProject/blob/rnowl-github-action/.github/workflows/ui-tests.yml), but [tests](https://github.com/shadowsheep1/TestRNOwlProject/actions/runs/4035931594) fail because the simulator time differs (It's not 9:41).

| iOS Tests fail due to time difference | 
| - |
| <img src="https://user-images.githubusercontent.com/16268789/215318755-a1b69862-50ac-4264-bb72-1a82193e35a8.png" width="600" /> |
| <img src="https://user-images.githubusercontent.com/16268789/215318821-eb44e1d2-6fab-487f-bdb2-bbd7e4e6bd2e.png" width="600" /> |

Can you help me understand what I'm missing?

**Comment by muhammadkhan0009** [comment]
Hello
First of all, thank you very much for doing such a great work on this library. Just want to write a comment here to support the above issue. I have explored the lib codebase for a bit and find out that  you have already fixed this issue a quite while ago in this PR https://github.com/FormidableLabs/react-native-owl/pull/16 but it seems issue is still there. Below implementation is not working as expected. Fixing this issue would be really helpful. 

Regards
Muhammad Khan
Software Engineer at Mixcloud
 
```
const SIMULATOR_TIME = '9:41';
const setTimeCommand = `xcrun simctl status_bar ${simulator} override --time ${SIMULATOR_TIME}`;
await execa.command(setTimeCommand, { stdio, cwd });
```

**Comment by muhammadkhan0009** [comment]
@shadowsheep1 
It seems like you are using xcode 14 or above version which is causing the issue.
The following changes would fix the issue: 
- Open xcode and tap on the `Xcode` on the top left corner. 
- Tap on  `Preferences`
- Tap on the `Platforms`
- Tap on the `+` at the bottom left
- Tap on `iOS`
- Download the `15.5` ios emulator
- Open the simulator iPhone 13 from the xcode and you are good to go.

**Comment by HERRKIN** [comment]
so it is not compatible with iOS 16?

**Comment by robwalkerco** [comment]
This seems to be an issue with iOS 16 (or 16.1) - https://developer.apple.com/forums/thread/720610
There is nothing that RN Owl can do itself to resolve this. 
While waiting for Apple to resolve this issue, you may need to continue to test on iOS 15

**Comment by robwalkerco** [comment]
Related to #165 

Is this still an issue?
I presume that it's resolved by Apple now that iOS Simulators 17.x are released

**Comment by robwalkerco** [comment]
Closing as it appears that this was resolved by newer ios simulator versions
