### ISSUE TITLE
Xcode 15.0 support

### ISSUE THREAD

**Issue by thep-dr** [FormidableLabs/react-native-owl#165]
Hi FormidableLabs,

Thank you for a great product.

I have a hard time spinning up tests when using Xcode 15. Is it something that should be supported?

It seems like it thinks that the Simulator has not been started, however, it is running.

Command:
`npx owl test --platform iOS`

Output:
```
[OWL - CLI] Starting websocket server.
[OWL - CLI] Running tests on ios.
Error: Command failed with exit code 149: xcrun simctl status_bar iPhone 14 override --time 9:41
    at makeError (/Users/xxx/Documents/xxx/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/xxx/Documents/xxx/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 149: xcrun simctl status_bar iPhone 14 override --time 9:41',
  command: 'xcrun simctl status_bar iPhone 14 override --time 9:41',
  escapedCommand: 'xcrun simctl status_bar "iPhone 14" override --time "9:41"',
  exitCode: 149,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Specify --help for available options

```

If I run the command failing command:
`xcrun simctl status_bar "iPhone 14" override --time 9:41`

Output:
```
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Unable to lookup in current state: Shutdown
```

**Comment by simplisticated** [comment]
I'm getting the same error. It's a huge blocker for the implementation of visual regression tests in a mobile app.

**Comment by Artem-Nanavov** [comment]
I have the same issue and found this. Maybe it can help you.

https://stackoverflow.com/questions/74507031/xcrun-simctl-status-bar-not-working-on-xcode-14-1

**Comment by Artem-Nanavov** [comment]
Yes, I found the solution, need to use this command before run test.

`SIMCTL_CHILD_SIMULATOR_RUNTIME_VERSION=16.4 xcrun simctl boot "<device name>"`

Example: `SIMCTL_CHILD_SIMULATOR_RUNTIME_VERSION=16.4 xcrun simctl boot "iPhone 14 Pro Max"`.

Read why this happening [here](https://stackoverflow.com/questions/74507031/xcrun-simctl-status-bar-not-working-on-xcode-14-1).

**Comment by robwalkerco** [comment]
Is this still an issue?
I presume that it's resolved by Apple now that iOS Simulators 17.x are released

**Comment by robwalkerco** [comment]
Closing as it appears that this was resolved by newer ios simulator versions
