### ISSUE TITLE
Screenshot is only for initial screen

### ISSUE THREAD

**Issue by gabimoncha** [FormidableLabs/react-native-owl#78]
ATM the screenshot can be taken only for the home screen. Ignoring the fact that some apps might stay longer in splash screen because of increasing startup time, there is no way of waiting for screens based on testID as in Detox or triggering any kind of actions.

**Comment by gabrielmoncea** [comment]
Detox already has the functionality to take screenshots. If an integration is possible, one solution could be for the library to wrap some of the Detox methods and take screenshots through it

**Comment by manosim** [comment]
Hi there, we've just published `v1.0.0` which brings in support for interacting with the simulator so moving forward you will be able to tap on buttons, scroll etc. More information in these methods can be found on the [documentation](https://formidable.com/open-source/react-native-owl/docs/api/methods/). Looking forward to your feedback!
