### ISSUE TITLE
iOS CI tests fail to run

### ISSUE THREAD

**Issue by gabimoncha** [FormidableLabs/react-native-owl#80]
Local tests are running, but CI tests don't

<img width="858" alt="Screenshot 2022-02-08 at 18 26 45" src="https://user-images.githubusercontent.com/39256258/153030969-7bfbcaeb-fa16-4a8a-ab85-39b805f1523e.png">

**Comment by robwalkerco** [comment]
Hi, it looks like you are starting a `iPhone 13 Pro` simulator, but trying to run the tests in an `iPhone 13` simulator. 
Please ensure you start the same simulator that you have configured for owl to use.
