### ISSUE TITLE
Issue with the methods import

### ISSUE THREAD

**Issue by simonedif** [FormidableLabs/react-native-owl#94]
The only method that I am able to use is `takeScreenshot`. 

![Screenshot 2022-05-23 at 16 30 30](https://user-images.githubusercontent.com/74412301/169856280-e7243eaf-1414-4289-b1da-a648b6f9568a.png)

I can see inside the lib/actions.ts all the listed methods which seem not correctly exported.

**Comment by sarahhamdi** [comment]
We are seeing the same issue! Any workaround or fix?

**Comment by manosim** [comment]
Hi both, thank you for reporting this issue. We'll take a look on this one as soon as possible.

**Comment by manosim** [comment]
Hi @simonedif and @sarahhamdi 👋 It looks like our docs were updated before we pushed the new version which is why you couldn't import these methods. I've just published `v1.0.0-rc1` which you can install with:

```
yarn add -D react-native-owl@next
```

Let me know if this doesn't fix the issue. Have a great day!
